version: '2'
services:
    web:
        build: .
        env_file: .env
        depends_on:
            - mongo
        environment:
            - PORT=3000
            - NODE_ENV=production
            - DATABASE_URL=mongodb://mongo/db
        ports:
            - "$PORT:3000"
    mongo:
        image: mongo
